name: astrokit
description: "A modern Flutter UI toolkit for building beautiful and responsive applications."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
